version: '3'

volumes:
    roomvu-mysql:

networks:
    backend:

services:
    nginx:
        image: nginx:stable
        container_name: roomvu-nginx-container
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - backend

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: roomvu-php-container
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        networks:
            - backend

    mysql:
        image: mysql:8.0
        container_name: roomvu-mysql-container
        restart: unless-stopped
        tty: true
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - '${DOCKER_DB_PORT}:3306'
        volumes:
            - roomvu-mysql:/var/lib/mysql
        networks:
            - backend

    composer:
        image: composer:2.2.6
        container_name: roomvu-composer-container
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - backend

    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: roomvu-artisan-container
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ 'php', '/var/www/html/artisan' ]
        networks:
            - backend
